"use client";
import { useEffect, useState } from "react";
import { prepareImage } from "./prepare-image";
import { money } from "@/lib/photo-pricing";
type Row=Record<string,any>;
async function api(path:string,method="GET",body?:unknown){const multipart=body instanceof FormData;const r=await fetch(path,{method,headers:body&&!multipart?{"Content-Type":"application/json"}:undefined,body:body?(multipart?body:JSON.stringify(body)):undefined});let d:any={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||`Request failed (${r.status}).`);return d}
function slug(name:string){return name.trim().toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,90)}
function paymentName(v:string){return v==="apple_cash"?"Apple Cash":v==="zelle"?"Zelle":"Cash"}
export default function AdminOperations({initialBookings}:{initialBookings:Row[]}){
 const[tab,setTab]=useState("Events"),[albums,setAlbums]=useState<Row[]>([]),[orders,setOrders]=useState<Row[]>([]),[bookings,setBookings]=useState(initialBookings),[name,setName]=useState(""),[date,setDate]=useState(""),[lightroom,setLightroom]=useState(""),[albumId,setAlbumId]=useState(""),[busy,setBusy]=useState(false),[notice,setNotice]=useState(""),[progress,setProgress]=useState("");
 async function loadAlbums(){const d=await api("/api/admin/albums");setAlbums(d.albums||[]);if(!albumId&&d.albums?.[0])setAlbumId(d.albums[0].id)}
 async function loadOrders(){const d=await api("/api/admin/orders");setOrders(d.orders||[])}
 useEffect(()=>{Promise.all([loadAlbums(),loadOrders()]).catch(e=>setNotice(e.message))},[]);
 async function run(fn:()=>Promise<void>){setBusy(true);setNotice("");try{await fn()}catch(e){setNotice(e instanceof Error?e.message:"Something went wrong.")}finally{setBusy(false);setProgress("")}}
 async function discover(){if(!lightroom.trim())throw new Error("Paste the Lightroom share link.");return api("/api/admin/lightroom/discover","POST",{url:lightroom.trim()})}
 async function importImage(eventId:string,img:Row){const check=await api(`/api/admin/media?album_id=${encodeURIComponent(eventId)}&source_type=lightroom&source_asset_id=${encodeURIComponent(img.id)}&page=0`);if(check.media?.length)return true;const r=await fetch(`/api/admin/lightroom/image?url=${encodeURIComponent(img.imageUrl)}`);if(!r.ok)throw new Error(`Could not download ${img.fileName||img.id}.`);const blob=await r.blob();const file=new File([blob],img.fileName||`lightroom-${img.id}.jpg`,{type:blob.type||"image/jpeg"});const form=await prepareImage(file);form.set("file",file);form.set("album_id",eventId);form.set("source_type","lightroom");form.set("source_asset_id",String(img.id));const result=await api("/api/admin/media","POST",form);return !!result.duplicate}
 async function sync(eventId:string){const d=await discover();const images=d.images||[];let added=0,existing=0;for(let i=0;i<images.length;i++){setProgress(`Syncing Lightroom ${i+1} / ${images.length}`);if(await importImage(eventId,images[i]))existing++;else added++}return{added,existing,total:images.length}}
 async function createAndSync(){await run(async()=>{if(!name.trim())throw new Error("Enter an event name.");setProgress("Checking Lightroom...");const d=await discover();if(!d.images?.length)throw new Error("No Lightroom photos found.");setProgress("Creating public event...");const a=await api("/api/admin/albums","POST",{name:name.trim(),slug:slug(name),gallery:"sports",event_date:date||null,is_private:false,is_visible:true,sort_order:0});setAlbumId(a.album.id);let added=0,existing=0;for(let i=0;i<d.images.length;i++){setProgress(`Importing ${i+1} / ${d.images.length}`);if(await importImage(a.album.id,d.images[i]))existing++;else added++}await loadAlbums();setNotice(`Public gallery ready. ${added} imported, ${existing} already existed.`);setName("");setDate("");setLightroom("")})}
 async function syncExisting(){await run(async()=>{if(!albumId)throw new Error("Choose an event.");const r=await sync(albumId);setNotice(`Sync complete. ${r.added} new photos, ${r.existing} already existed.`)})}
 async function markPaid(id:string){await run(async()=>{const d=await api(`/api/admin/orders/${id}/paid`,"POST",{});await loadOrders();setNotice(d.email_sent?`Paid. Client gallery created and emailed.`:`Paid. Client gallery created. Delivery email was not sent; copy the gallery link from the order.`)})}
 async function updateBooking(id:string,status:string){const d=await api(`/api/admin/bookings/${id}`,"PATCH",{status});setBookings(c=>c.map(x=>x.id===id?d.booking:x))}
 return <main className="page-shell"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="eyebrow">LKC Media Operations</p><h1>Admin</h1></div><a href="/api/admin/logout" className="text-sm text-slate-400">Log out</a></div>
 <div className="mt-8 flex gap-2">{["Events","Orders","Bookings"].map(x=><button key={x} onClick={()=>setTab(x)} className={`rounded-full px-4 py-2 text-sm ${tab===x?"bg-blue-600 text-white":"bg-white/5 text-slate-300"}`}>{x}{x==="Orders"&&orders.filter(o=>o.payment_status==="pending").length?` (${orders.filter(o=>o.payment_status==="pending").length})`:""}</button>)}</div>
 {(notice||progress)&&<div className="mt-6 rounded-xl border border-white/10 bg-white/5 p-4 text-sm">{progress||notice}</div>}
 {tab==="Events"&&<><section className="mt-8 rounded-2xl border border-blue-500/20 bg-blue-500/[0.05] p-6"><p className="eyebrow">New public gallery</p><h2 className="mt-2 text-2xl font-semibold">Lightroom → Storefront</h2><div className="mt-5 grid gap-3 md:grid-cols-2"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Event name" className="rounded-xl border border-white/10 bg-black px-4 py-3"/><input type="date" value={date} onChange={e=>setDate(e.target.value)} className="rounded-xl border border-white/10 bg-black px-4 py-3"/></div><input value={lightroom} onChange={e=>setLightroom(e.target.value)} placeholder="https://adobe.ly/..." className="mt-3 w-full rounded-xl border border-white/10 bg-black px-4 py-3"/><button disabled={busy||!name.trim()||!lightroom.trim()} onClick={createAndSync} className="mt-4 rounded-xl bg-blue-600 px-5 py-3 font-semibold disabled:opacity-40">CREATE + SYNC PUBLIC GALLERY</button></section>
 <section className="mt-8"><h2 className="text-2xl font-semibold">Events</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{albums.map(a=><article key={a.id} className="rounded-2xl border border-white/10 bg-white/[0.03] p-5"><h3 className="text-xl font-semibold">{a.name}</h3><p className="mt-1 text-sm text-slate-400">{a.event_date||"No date"} · {a.is_visible?"Public":"Hidden"}</p><div className="mt-4 flex flex-wrap gap-2"><a href={`/gallery/${a.slug}`} target="_blank" className="rounded-lg bg-blue-600 px-3 py-2 text-sm">Open gallery</a><button onClick={()=>{setAlbumId(a.id);setLightroom("");}} className={`rounded-lg px-3 py-2 text-sm ${albumId===a.id?"bg-white/20":"bg-white/10"}`}>Select for sync</button></div></article>)}</div><div className="mt-5 rounded-2xl border border-white/10 p-4"><select value={albumId} onChange={e=>setAlbumId(e.target.value)} className="w-full rounded-xl bg-black px-4 py-3">{albums.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select><input value={lightroom} onChange={e=>setLightroom(e.target.value)} placeholder="Paste Lightroom link to add new photos" className="mt-3 w-full rounded-xl border border-white/10 bg-black px-4 py-3"/><button disabled={busy||!albumId||!lightroom.trim()} onClick={syncExisting} className="mt-3 rounded-xl bg-white/10 px-4 py-3 text-sm disabled:opacity-40">SYNC NEW PHOTOS</button></div></section></>}
 {tab==="Orders"&&<section className="mt-8"><div className="flex items-end justify-between"><div><p className="eyebrow">Photo sales</p><h2 className="text-2xl font-semibold">Orders</h2></div><button onClick={()=>run(loadOrders)} className="rounded-lg bg-white/10 px-3 py-2 text-sm">Refresh</button></div><div className="mt-5 space-y-3">{orders.map(o=>{const album=Array.isArray(o.albums)?o.albums[0]:o.albums;const collection=Array.isArray(o.client_collections)?o.client_collections[0]:o.client_collections;return <article key={o.id} className="rounded-2xl border border-white/10 bg-white/[0.03] p-5"><div className="flex flex-wrap justify-between gap-4"><div><div className="flex items-center gap-2"><h3 className="text-lg font-semibold">{o.order_number}</h3><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${o.payment_status==="paid"?"bg-green-500/15 text-green-300":"bg-amber-500/15 text-amber-300"}`}>{o.payment_status==="paid"?"PAID":"AWAITING PAYMENT"}</span></div><p className="mt-2 text-sm text-slate-300">{o.customer_name} · {o.customer_email}{o.customer_instagram?` · ${o.customer_instagram}`:""}</p><p className="mt-1 text-sm text-slate-400">{album?.name||"Event"} · {o.photo_count} photos · {money(o.amount_cents)} · {paymentName(o.payment_method)}</p></div><div className="flex items-center gap-2">{o.payment_status!=="paid"?<button disabled={busy} onClick={()=>markPaid(o.id)} className="rounded-xl bg-green-600 px-4 py-3 text-sm font-semibold">MARK PAID + DELIVER</button>:collection?.share_token?<a target="_blank" href={`/client/c/${collection.share_token}`} className="rounded-xl bg-blue-600 px-4 py-3 text-sm">Open client gallery</a>:null}</div></div></article>})}{!orders.length&&<div className="rounded-2xl border border-dashed border-white/10 p-10 text-center text-slate-400">No photo orders yet.</div>}</div></section>}
 {tab==="Bookings"&&<section className="mt-8 space-y-3">{bookings.map(b=><article key={b.id} className="rounded-xl border border-white/10 bg-white/5 p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="font-semibold">{b.name}</h2><p className="text-sm text-slate-400">{b.email} · {b.shoot_type}</p></div><select value={b.status||"new"} onChange={e=>updateBooking(b.id,e.target.value)} className="rounded-lg bg-black px-3 py-2">{["new","contacted","confirmed","completed","cancelled"].map(s=><option key={s}>{s}</option>)}</select></div></article>)}</section>}
 </main>
}
